config/routes.rb
Fluxqc::Application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get "measurements/show"
  resources :templates

  devise_for :users

  resources :runs do
    collection do
      get 'all'
    end
    member do
      get  'gcinput'
      get  'standard_curves'
      get  'updated_at'
      post 'reject'
      post 'accept'
      post 'approve'
      post 'publish'
      post 'unapprove'
      post 'unpublish'
      post 'unreject'
      post 'park'
    end
  end


  resources :incubations 
  resources :fluxes
  resources :standard_curves, only: [:show, :update]
  resources :setups
  resources :samples

  resources :measurements, only: :index

  # authenticated(:user) do
  #   mount Resque::Server, :at => "/resque"
  # end
 
  get "runs/:id/standards" => 'runs#show'
  root :to => 'runs#index'
end

app/views/templates/_form.html.erb
<%= simple_form_for(@template) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :study %>
    <%= f.input :plots %>
    <%= f.input :samples_per_plot %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<h1>Listing templates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Study</th>
    <th>Plots</th>
    <th>Samples per plot</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @templates.each do |template| %>
  <tr>
    <td><%= template.name %></td>
    <td><%= template.study %></td>
    <td><%= template.plots %></td>
    <td><%= template.samples_per_plot %></td>
    <td><%= link_to 'Show', template %></td>
    <td><%= link_to 'Edit', edit_template_path(template) %></td>
    <td><%= link_to 'Destroy', template, data: {confirm: 'Are you sure?'}, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @template.name %>
</p>

<p>
  <b>Study:</b>
  <%= @template.study %>
</p>

<p>
  <b>Plots:</b>
  <%= @template.plots %>
</p>

<p>
  <b>Samples per plot:</b>
  <%= @template.samples_per_plot %>
</p>


<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>