config/routes.rb
Fluxqc::Application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get "measurements/show"
  resources :templates

  devise_for :users

  resources :runs do
    collection do
      get 'all'
    end
    member do
      get  'gcinput'
      get  'standard_curves'
      get  'updated_at'
      post 'reject'
      post 'accept'
      post 'approve'
      post 'publish'
      post 'unapprove'
      post 'unpublish'
      post 'unreject'
      post 'park'
    end
  end


  resources :incubations 
  resources :fluxes
  resources :standard_curves, only: [:show, :update]
  resources :setups
  resources :samples

  resources :measurements, only: :index

  # authenticated(:user) do
  #   mount Resque::Server, :at => "/resque"
  # end
 
  get "runs/:id/standards" => 'runs#show'
  root :to => 'runs#index'
end

app/models/run.rb
# frozen_string_literal: true

require 'workflow'

# The Run class is the root class of the system.
# It holds references to incubations and standards.
# A run represents one sampling time. It consists of all of the samples
# taken during a sampling event on a particular study
class Run < ActiveRecord::Base
  include WorkflowActiverecord

  belongs_to :company
  has_many :incubations, -> { order 'treatment, replicate' }, dependent: :destroy
  has_many :samples, dependent: :destroy
  has_many :standard_curves, dependent: :destroy
  # has_many :data_files, dependent: :destroy

  mount_uploader :setup_file, SetupUploader
  # mount_uploader :data_file, DataUploader
  mount_uploaders :data_files, DataUploader

  accepts_nested_attributes_for :incubations, :samples

  scope :by_state, ->(state) { where(workflow_state: state) }

  after_save :recompute_fluxes

  workflow do
    state :uploaded do
      event :accept,  transitions_to: :accepted
      event :park,    transitions_to: :parked
    end
    state :accepted do
      event :approve, transitions_to: :approved
      event :reject,  transitions_to: :rejected
    end
    state :approved do
      event :publish, transitions_to: :published
      event :reject,  transitions_to: :rejected
      event :unapprove, transitions_to: :accepted
    end
    state :published do
      event :unpublish, transitions_to: :approved
    end
    state :rejected do
      event :unreject, transitions_to: :uploaded
    end
    state :parked do
      event :unpark, transitions_to: :uploaded
    end
    on_transition do |_from, _to, _triggering_event, *_event_args|
      touch if persisted?
    end
  end

  def total_fluxes
    incubations.count * 3
  end

  def publish
    self.released = true
  end

  def unpublish
    self.released = false
  end

  def upload
    self.uploaded = true
  end

  def recompute_fluxes
    incubations.each(&:recompute_fluxes)
  end

  def measurements_for(compound)
    incubations.collect { |incubation| incubation.measurements_for(compound) }.flatten
  end

  def standard_curves_for(compound, column = 0)
    standard_curves.select { |x| x.compound == compound && x.column == column }
  end

  def attach_standards_to_samples
    # TODO: remove this once references have been removed
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController

  respond_to :html, :json, :csv

  def index
    params[:state] ||= 'uploaded'
    @state = params[:state]
    @runs = Run.by_state(@state).order('sampled_on desc')
  end

  def all
    @runs = Run.where('company_id != 2').order('study').order('sampled_on desc')
    render :index
  end

  def show
    @run = run
    @state = @run.current_state.name.to_s

    @incubations = @run.incubations
    @standard_curves = @run.standard_curves.order('created_at')
    respond_with do |format|
      format.html { render layout: 'qc' }
      format.json { render json: @incubations }
    end
  end

  def new
    @run = Run.new
  end

  def create
    @run = Run.new(run_params)
    @run.company = current_user.company
    if @run.save
      if params[:run][:setup_file]
        # if Rails.env == 'production'
        #   Resque.enqueue(SetupFileLoader, @run.id)
        # else
        SetupFileLoader.perform(@run.id)
        # end
      end
      if params[:run][:data_files]
        # if Rails.env == 'production'
        #   Resque.enqueue(DataFileLoader, @run.id)
        # else
        DataFileLoader.perform(@run.id)
        # end
      end
      if params[:run][:setup_file] && params[:run][:data_files]
        redirect_to run_path(@run)
      else
        redirect_to edit_run_path(@run)
      end
    else
      redirect_to new_run_path
    end
  end

  def edit
    @run = Run.includes(samples: [{ incubation: :lid }, { measurements: :compound }])
              .find(params[:id])
    @state = @run.current_state.name.to_s
    respond_with do |format|
      format.html { render layout: 'qc' }
    end
  end

  def update
    @run = run
    if @run.update_attributes(run_params)
      if params[:run][:setup_file]
        # if Rails.env == 'production'
        #   Resque.enqueue(SetupFileLoader, @run.id)
        # else
        SetupFileLoader.perform(@run.id)
        # end
      end
      if params[:run][:data_files]
        # if Rails.env == 'production'
        #   Resque.enqueue(DataFileLoader, @run.id)
        # else
        DataFileLoader.perform(@run.id)
        # end
      end
      redirect_to run_path(@run)
    else
      redirect_to edit_run_path(@run)
    end
  end

  def gcinput
    @run = run
  end

  def updated_at
    render plain: run.updated_at
  end

  def reject
    run.reject!
    redirect_to runs_path(state: 'rejected')
  end

  def standard_curves
    head :ok
    # render nothing: true
    # run = Run.find(params[:id])

    # respond_with do |format|
    #   format.json {render :json =>
    #     run.standard_curves.to_json(:methods =>
    #                                 ['data','ymax','ymin','multiplier',
    #                                   'fit_line','slope'])}
    # end
  end

  def accept
    run.accept!
    redirect_to runs_path(state: 'uploaded')
  end

  def approve
    run.approve!
    redirect_to runs_path(state: 'accepted')
  end

  def publish
    run.publish!
    redirect_to runs_path(state: 'approved')
  end

  def unapprove
    run.unapprove!
    redirect_to runs_path(state: 'approved')
  end

  def unpublish
    run.unpublish!
    redirect_to runs_path(state: 'published')
  end

  def unreject
    run.unreject!
    redirect_to runs_path(state: 'rejected')
  end

  def destroy
    Run.destroy(params[:id])
    redirect_to runs_path(state: 'uploaded')
  end

  def park
    run.park!
    redirect_to runs_path(state: 'uploaded')
  end

  private

  def run
    Run.find(params[:id])
  end

  def run_params
    params.require(:run).permit!
    # (:name, :sampled_on, :run_on, :comment, :study, :setup_file, :data_file, incubations_attributes: [{:samples_attributes}], :setup_file_cache, :data_file_cache)
  end
end

app/views/runs/_form.html.erb
<%= f.input :sampled_on , :label=>'Sample Date' , :as => :string, :input_html =>{ :class=>'span2', :datepicker=>'datepicker' }%>
<%= f.input :run_on, :label=>'Run Date', :as => :string, :input_html=>{:class=>'span2', :datepicker=>'datepicker'} %>
<%= f.input :name %>
<%= f.input :study %>
<%= f.input :comment, :input_html => {  :rows => 5 } %>
<div>
  <label>Setup File</label>
  <%= link_to @run.setup_file, @run.setup_file_url, :class=>'uploaded_file' if @run.setup_file? %>
  <%= f.file_field :setup_file, input_html: {class: 'btn btn-default btn-file'} %>
  <%= f.hidden_field :setup_file_cache %>
</div>
<div>
  <label>Data Files</label>
  <% @run.data_files.each do |data_file| %>
    <%= link_to data_file, data_file.url, :class=>'uploaded_file' %><br/>
  <% end %>
  <%= f.file_field :data_files, multiple: true, input_html: {class: 'btn btn-default btn-file'} %>
  <%= f.hidden_field :data_files_cache %>
</div>

<div>
  <%= link_to 'back to index', runs_path, :class=>'btn' %>
  <%= f.button :submit , :class=>'btn btn-primary'%>
</div>

app/views/runs/_run.html.erb
<% cache(run) do %>
  <tr> 
    <td><%= run.run_on %></td>
    <td><%= run.sampled_on %></td>
    <td><%= run.name %></td>
    <td><%= run.comment %></td>
    <td><%= run.workflow_state %></td>
    <td><%= run.study %></td>
    <td><%= "#{run.total_fluxes}" %></td>
    <td>
      <% if run.setup_file.current_path && run.data_files.size == 0%>
        <i class="fa fa-square-o"></i>
      <% end %>
      <% if run.data_files.size > 0 && !run.setup_file.current_path%>
          <i class="fa fa-check"></i>
        <% end %>
        <% if run.data_files.size > 0&& run.setup_file.current_path%>
        <i class="fa fa-check-square-o"></i>
        <% end %>
    </td>
    <td><%= link_to 'qc', run ,:class =>'btn btn-success'%></td>
    <td><%= link_to '', edit_run_path(run), :class=>'btn btn-default fa fa-pencil-square-o' %></td>
    <td><%= link_to '', run_url(run, :format => :csv), :class=>'btn btn-default fa fa-download' %></td>
    <td><%= link_to 'gc input', gcinput_run_url(run, :format=>:csv), :class=>'btn btn-default' %></td>
    <td><%= link_to 'destroy',  run, method: :delete, data: {confirm: "Are you sure you want to delete the #{run.name}?" } ,class: 'btn btn-default'%></td>
  </tr>
<% end %>

app/views/runs/edit.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<%= link_to "download raw data", run_path(@run.id, :csv) %>
<%= simple_form_for @run do |f| %>
  <%= render 'form', :f => f %>
<% end %>
<% cache(@run) do %>
<table class='table table-condensed'>
  <thead>
    <tr>
      <th>Treatment</th>
      <th>Replicate</th>
      <th>Chamber</th>
      <th>Sub plot</th>
      <th>Lid</th>
      <th>Avg. Chamber Height cm</th>
      <th>Soil Temperature</th>
      <th>Vials</th>
      <th>Minutes</th>
      <th>N2O ppm</th>
      <th>CO2 ppm</th>
      <th>CH4 ppm</th>
    </tr>
  </thead>
  <tbody>
    <% @run.incubations.each do |incubation| %>
      <% rows = 9 %>
      <tr data-incubation-id=<%=incubation.id %>>
        <td rowspan=<%=rows%>><%= link_to incubation.treatment, edit_incubation_path(incubation) %></td>
        <td rowspan=<%=rows%>><%= incubation.replicate %></td>
        <td rowspan=<%=rows%>><%= incubation.chamber %></td>
        <td rowspan=<%=rows%>><%= incubation.sub_plot %></td>
        <td rowspan=<%=rows%>><%= incubation.lid.try(:name) %></td>
        <td rowspan=<%=rows%> class=<%= (incubation.avg_height_cm.nil? || incubation.avg_height_cm == 0) ? 'danger' : ''%>><%= number_with_precision(incubation.avg_height_cm, precision: 1)%></td>
        <td rowspan=<%=rows%>><%= incubation.soil_temperature %></td>
        <% incubation.samples.each do |sample| %>
          <tr>
            <td><%= sample.vial %></td>
            <td><%= sample.seconds %> </td>
            <td><%= sample.data('n2o').try(:ppm) %></td>
            <td><%= sample.data('co2').try(:ppm) %></td>
            <td><%= sample.data('ch4').try(:ppm) %></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td><%= sample.data('n2o').try(:area) %></td>
            <td><%= sample.data('co2').try(:area) %></td>
            <td><%= sample.data('ch4').try(:area) %></td>
          </tr>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<div class='hidden'>

  <tr>
    <% rows = 9 %>
    <td rowspan=<%=rows%>><input type=text name='treatment'></td>
    <td rowspan=<%=rows%>><input type=text name='replicate'></td>
    <td rowspan=<%=rows%>><input type=text name='chamber'></td>
    <td rowspan=<%=rows%>><input type=text name='sub_plot'></td>
    <td rowspan=<%=rows%>><input type=text name='lid'></td>
    <td rowspan=<%=rows%>><input type=text name='avg_height_cm'><td>
        <td rowspan=<%=rows%>><input type=text name='soil_temperature'></td>
  </tr>
</div>

<div class='hidden'>
  <tr>
    <td><input type=text name='sample_vial'></td>
    <td><input type=text name='seconds'> </td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  </tr>
</div>

app/views/runs/gcinput.csv.erb
1,,air, Standard,
2,,4nt, Standard,
3,,4.5nt, Standard,
<% i = 4 %>
<% @run.samples.each do |sample| %>
  <%= i %>,<%= sample.vial %>, Sample, <%= sample.uuid %>
  <% if (i % 10 == 0) %>
    <% i = i + 1 %>
<%= i %>, Chk, Sample 
  <% end %> 
  <% i = i + 1 %>
<% end %>
<%= i %>,,air, Standard,
<% i = i + 1 %>
<%= i %>,,4nt, Standard,
<% i = i + 1 %>
<%= i %>,,4.5nt, Standard,

app/views/runs/index.html.erb
<%= link_to 'new run', new_run_path, :class=>'btn' %>
<table class="table table-condensed table-striped">
  <tr>
    <th>Run Date</th>
    <th>Sample Date</th>
    <th>Name</th>
    <th>Comment</th>
    <th>State</th>
    <th>Study</th>
    <th>Fluxes</th>
  </tr>
  <%= render @runs %>
</table>
<%= link_to 'new run', new_run_path, :class=>'btn' %>

app/views/runs/new.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<%= simple_form_for @run do |f| %>
  <%= render 'form', :f => f %>
<% end %> 

app/views/runs/show.csv.erb
sampled_on, study, treatment, replicate, lid, minutes, ppm, area, avg_height_cm, compound
<% @run.incubations.each do |incubation | %>
  <% ['n2o','co2','ch4'].each do |compound| %>
    <% incubation.flux(compound).measurements.each do |c| %>
      <% next if c.excluded? %>
      <%= "#{@run.sampled_on},#{@run.study},#{incubation.treatment},#{incubation.replicate},#{incubation.lid.try(:name)},#{c.seconds}, #{c.ppm}, #{c.area}, #{incubation.avg_height_cm},#{compound}" %>
    <% end %>
  <% end %>
<% end %>
<% Compound.all.each do |compound| %>
  <% @run.standard_curves.where(compound: compound).each do |curve| %>
    <% curve.standards.where(compound: compound).each do | standard| %>
      <% next if standard.excluded? %>
      <%= "#{@run.sampled_on},#{@run.study},standard,#{curve.id},#{standard.id},, #{standard.ppm},#{standard.area}, ,#{compound.try(:name)}" %>
    <% end %>
  <% end %>
<% end %>

app/views/runs/show.html.erb
<h3><%= @run.name %> <%=@run.sampled_on %></h3>
<ul class="nav nav-tabs">
  <li id='standard-tab'><%= link_to 'Standards', run_path(@run) + '/standards' %></li>
  <li id='sample-tab' class='active'><%= link_to 'Samples', run_path(@run) %></li>
</ul>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<div id='container'>Loading...</div>

<script>
  INITIAL_DATA = <%= raw json_for @incubations %>;
  INITIAL_STANDARD_DATA = <%= raw json_for @standard_curves %>;
  window.run_id = <%= @run.id %>
  $(function() {
    window.myApp = new Flux.Routers.FluxesRouter;
    Backbone.history.start({pushState: true, root: '/runs/' + window.run_id});
  });
</script>

<script type='text/template' id='flux-list-template'>
  <h1>Model Fluxes</h1>
  <ul class='flux'></ul>
</script>

<script type='text/template' id='incubation-template'>
  <a href='/incubations/{{id}}/edit' class='treatment-label'>{{ name }}</a>
</script>

<script type='text/template' id='standard-list-template'>
  <ul class='flux'></ul>
</script>

<script type='text/template' id='standard-template'>
  <div> ppm = {{ slope }} * area + {{ offset }} 
    <span class='graph'></span>
  </div>
</script>

<script type='text/template' id='equation-template'>
  {{ slope.toExponential(3) }} * A + {{ offset.toExponential(3) }}
</script>