config/routes.rb
Fluxqc::Application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get "measurements/show"
  resources :templates

  devise_for :users

  resources :runs do
    collection do
      get 'all'
    end
    member do
      get  'gcinput'
      get  'standard_curves'
      get  'updated_at'
      post 'reject'
      post 'accept'
      post 'approve'
      post 'publish'
      post 'unapprove'
      post 'unpublish'
      post 'unreject'
      post 'park'
    end
  end


  resources :incubations 
  resources :fluxes
  resources :standard_curves, only: [:show, :update]
  resources :setups
  resources :samples

  resources :measurements, only: :index

  # authenticated(:user) do
  #   mount Resque::Server, :at => "/resque"
  # end
 
  get "runs/:id/standards" => 'runs#show'
  root :to => 'runs#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fluxqc</title>
    <script src="https://use.fontawesome.com/bd18aea090.js"></script>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-default" role="navigator">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="#">FluxQC</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li <%="class=active" if @state == 'uploaded'%> ><%= link_to 'Uploaded', runs_url({:state => :uploaded}) %></li>
            <li <%="class=active" if @state == 'accepted'%> ><%= link_to 'Accepted', runs_url({:state => :accepted}) %></li>
            <li <%= "class=active" if @state == 'approved'%> ><%= link_to 'Approved', runs_url({:state => :approved}) %></li>
            <li <%= "class= active" if @state == 'published'%> ><%= link_to 'Published', runs_url({:state => :published}) %></li>
            <li <%= "class= active" if @state == 'rejected'%> ><%= link_to 'Rejected', runs_url({:state=>:rejected}) %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Sign In', new_user_session_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
  </div>

  <!--[if lt IE 9]>
  <div class='alert'>
    outdated versions of internet explorer are not supported
  </div>
  <![endif]-->
  <div class='container-fluid'>
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/qc.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fluxqc</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-default" role="navigator">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="#">FluxQC</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li <%= "class=active" if @state == 'uploaded'%> ><%= link_to 'Uploaded', runs_url({:state => :uploaded}) %></li>
            <li <%= "class=active" if @state == 'accepted'%> ><%= link_to 'Accepted', runs_url({:state => :accepted}) %></li>
            <li <%= "class=active" if @state == 'approved'%> ><%= link_to 'Approved', runs_url({:state => :approved}) %></li>
            <li <%= "class=active" if @state == 'published'%> ><%= link_to 'Published', runs_url({:state => :published}) %></li>
            <li <%= "class=active" if @state == 'rejected'%> ><%= link_to 'Rejected', runs_url({:state=>:rejected}) %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Sign In', new_user_session_path  %></li>
            <% end %>
          </ul>
          <ul class='nav pull-right'>
            <% @run.current_state.events.keys.each do |event| %>
              <li class='workflow'><%=button_to "#{event.to_s}", action: event %></li>
            <% end %>
          </ul>
          <ul class='nav pull-right'>
            <li><%= link_to 'edit', edit_run_path(@run) if params[:action]=='show' %></li>
            <li><%= link_to 'qc', run_path(@run) if params[:action]=='edit' %></li>
          </ul>
          <ul class='nav pull-right'>
            <li> <%= @run.name %></li>
          </ul>
        </div>
      </div>
    </div>
  <div class='container-fluid'>
    <%= yield %>
  </div>

</body>
</html>